export const COPY = {
  appName: 'Ajinkyans',
  batchName: 'Sainik School Satara · 2002 Batch',
  signIn: 'Continue with Google',
  privateAccess: 'Our memories, preserved—privately for approved members.',
  cancel: 'Cancel',
  working: 'Working…',
  dialogActionFailed: 'Could not complete that action. Please try again.',
  shell: {
    signOut: 'Sign out',
  },
  resilience: {
    offline: 'You’re offline. Previously opened app screens remain available; private data will refresh when you reconnect.',
    errorTitle: 'Something went wrong',
    errorBody: 'Please refresh the app. If this continues, contact a Coordinator.',
  },
  reunion: {
    announced: 'Reunion details will be shared here.',
    rsvpClosed: 'RSVP is closed. View the confirmed reunion details.',
    completed: 'The reunion has concluded. Relive the memories.',
    archived: 'This reunion is now part of the archive.',
    homeEyebrow: 'Silver Jubilee reunion',
    homeFallbackTitle: 'Date to be announced',
    homeCountdownSuffix: 'until we return to Satara.',
    viewReunion: 'View reunion',
    rsvp: 'RSVP now',
    viewDetails: 'View details',
    viewSchedule: 'View schedule',
    viewMemories: 'View memories',
    getNotified: 'Get reunion updates',
    unavailableTitle: 'Reunion unavailable',
    unavailableBody: 'Check your connection and try again. Private reunion details are not shown until they load.',
    permissionTitle: 'Reunion unavailable',
    permissionBody: 'Your membership no longer permits this reunion information. Contact a Coordinator if this is unexpected.',
    retry: 'Try again',
    schedule: 'Schedule',
    scheduleEmpty: 'The detailed schedule will be added by a Coordinator.',
    calendar: 'Add to calendar',
    fundTitle: 'Reunion fund',
    fundBody: 'Contributions and approved-expense reporting live inside the reunion hub.',
    fundAction: 'View reunion fund',
    attendance: (yes: number, maybe: number) => `${yes} confirmed · ${maybe} maybe`,
    rsvpTitle: 'RSVP',
    rsvpPrompt: 'Please let the Coordinators know your plans.',
    rsvpCutoff: (date: string) => `Please respond by ${date}.`,
    saveRsvp: 'Save RSVP',
    rsvpSaved: 'RSVP saved.',
    rsvpFailed: 'Unable to save RSVP. Please try again.',
    venueTitle: 'Venue and arrival',
    directions: 'Open directions in Maps',
  },
  paymentClaim: {
    draft: 'Your payment claim is ready to submit.', submitted: 'Your claim has been submitted.', underReview: 'A Coordinator is reviewing your claim.', clarificationRequired: 'Please correct the requested payment details.', verified: 'Your payment has been verified.', rejected: 'Your claim could not be verified. Please correct and resubmit it.', resubmitted: 'Your corrected claim has been resubmitted.',
  },
  coordinator: {
    checkingAccess: 'Checking Coordinator access…',
    accessChanged: 'Your Coordinator access is no longer available. Batch member access remains unchanged.',
  },
  superAdmin: {
    label: 'Super Admin',
    title: 'Governance console',
    intro: 'Manage Coordinator access and review authoritative governance activity.',
    signOut: 'Sign out securely',
    directoryLabel: 'Coordinator access',
    directoryTitle: 'Active member directory',
    searchLabel: 'Search active members',
    searchPlaceholder: 'Name, email, or member code',
    search: 'Search',
    loadingMembers: 'Loading active members…',
    membersEmpty: 'No active members match this search.',
    membersFailed: 'The member directory could not be loaded. Please try again.',
    accessDenied: 'Access denied. Your Super Admin session may have expired.',
    retryMembers: 'Retry member directory',
    loadMoreMembers: 'Load more members',
    coordinator: 'Coordinator',
    member: 'Member',
    appoint: 'Appoint',
    revoke: 'Revoke',
    appointAria: (name: string) => `Appoint Coordinator for ${name}`,
    revokeAria: (name: string) => `Revoke Coordinator from ${name}`,
    appointTitle: 'Appoint Coordinator',
    revokeTitle: 'Revoke Coordinator',
    appointDescription: 'This grants the member Coordinator authority immediately.',
    revokeDescription: 'This removes the member’s Coordinator authority immediately.',
    reasonLabel: 'Business reason',
    reasonRequired: 'A business reason is required.',
    appointed: 'Coordinator appointed.',
    revoked: 'Coordinator revoked.',
    noChange: 'No role change was needed.',
    roleChangeFailed: 'The Coordinator role could not be updated. Please try again.',
    bootstrapLabel: 'Zero-Coordinator recovery',
    bootstrapTitle: 'Coordinator bootstrap',
    bootstrapIntro: 'Approve one pending applicant and appoint them as the first Coordinator.',
    loadingBootstrap: 'Loading pending applicants…',
    bootstrapEmpty: 'No pending applicants are available for Coordinator bootstrap.',
    bootstrapFailed: 'The bootstrap candidates could not be loaded. Please try again.',
    retryBootstrap: 'Retry bootstrap candidates',
    loadMoreCandidates: 'Load more applicants',
    appointBootstrap: 'Approve and appoint Coordinator',
    appointBootstrapAria: (name: string) => `Approve and appoint Coordinator for ${name}`,
    appointBootstrapDescription: 'This approves the pending applicant and grants Coordinator authority immediately.',
    bootstrapSuccess: 'Coordinator appointed. The bootstrap panel is no longer available.',
    bootstrapStale: 'Coordinator bootstrap is no longer available because the selected applicant is no longer eligible.',
    bootstrapDuplicateRoll: 'That school roll number is already assigned to another active member. Choose another applicant or resolve the duplicate roll number.',
    bootstrapRetry: 'Could not appoint the Coordinator. Please try again.',
    auditLabel: 'Authoritative audit log',
    auditTitle: 'Governance activity',
    actionLabel: 'Audit action',
    allActions: 'All actions',
    actorLabel: 'Actor UID',
    targetLabel: 'Target UID',
    fromLabel: 'From date',
    toLabel: 'To date',
    applyFilters: 'Apply audit filters',
    loadingAudit: 'Loading audit events…',
    retryAudit: 'Retry audit log',
    auditEmpty: 'No audit events match these filters.',
    loadMoreAudit: 'Load more audit events',
    actor: 'Actor',
    target: 'Target',
    reason: 'Reason',
    timestampPending: 'Timestamp pending',
  },
} as const
