export const COPY = {
  appName: 'Ajinkyans',
  batchName: 'Sainik School Satara · 2002 Batch',
  signIn: 'Continue with Google',
  privateAccess: 'Our memories, preserved—privately for approved members.',
  offlinePrivateData: 'private data will refresh when you reconnect',
  cancel: 'Cancel',
  working: 'Working…',
  dialogActionFailed: 'Could not complete that action. Please try again.',
  superAdmin: {
    label: 'Super Admin',
    title: 'Governance console',
    intro: 'Manage Coordinator access and review authoritative governance activity.',
    signOut: 'Sign out securely',
    directoryLabel: 'Coordinator access',
    directoryTitle: 'Active member directory',
    searchLabel: 'Search active members',
    searchPlaceholder: 'Name, email, or member code',
    search: 'Search',
    loadingMembers: 'Loading active members…',
    membersEmpty: 'No active members match this search.',
    membersFailed: 'The member directory could not be loaded. Please try again.',
    accessDenied: 'Access denied. Your Super Admin session may have expired.',
    retryMembers: 'Retry member directory',
    loadMoreMembers: 'Load more members',
    coordinator: 'Coordinator',
    member: 'Member',
    appoint: 'Appoint',
    revoke: 'Revoke',
    appointAria: (name: string) => `Appoint Coordinator for ${name}`,
    revokeAria: (name: string) => `Revoke Coordinator from ${name}`,
    appointTitle: 'Appoint Coordinator',
    revokeTitle: 'Revoke Coordinator',
    appointDescription: 'This grants the member Coordinator authority immediately.',
    revokeDescription: 'This removes the member’s Coordinator authority immediately.',
    reasonLabel: 'Business reason',
    reasonRequired: 'A business reason is required.',
    appointed: 'Coordinator appointed.',
    revoked: 'Coordinator revoked.',
    noChange: 'No role change was needed.',
    roleChangeFailed: 'The Coordinator role could not be updated. Please try again.',
    auditLabel: 'Authoritative audit log',
    auditTitle: 'Governance activity',
    actionLabel: 'Audit action',
    allActions: 'All actions',
    actorLabel: 'Actor UID',
    targetLabel: 'Target UID',
    fromLabel: 'From date',
    toLabel: 'To date',
    applyFilters: 'Apply audit filters',
    loadingAudit: 'Loading audit events…',
    retryAudit: 'Retry audit log',
    auditEmpty: 'No audit events match these filters.',
    loadMoreAudit: 'Load more audit events',
    actor: 'Actor',
    target: 'Target',
    reason: 'Reason',
    timestampPending: 'Timestamp pending',
  },
} as const
