import { FormEvent, useEffect, useState } from 'react'
import { collection, doc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore'
import { httpsCallable } from 'firebase/functions'
import { firebaseServices } from '../lib/firebase'
import { HOUSES, PILOT_BATCH_ID } from '../lib/membership'

type Member = { uid: string; role?: string; status: string; houseId?: string; displayName?: string }
type AccessRequest = { id: string; uid: string; displayName: string; houseId?: string }
export function CoordinatorPage() {
  const [members, setMembers] = useState<Member[]>([]); const [requests, setRequests] = useState<AccessRequest[]>([]); const [notice, setNotice] = useState('')
  const refresh = async () => { const db = firebaseServices().db; const [memberDocs, requestDocs] = await Promise.all([getDocs(collection(db, `batches/${PILOT_BATCH_ID}/memberships`)), getDocs(collection(db, `batches/${PILOT_BATCH_ID}/accessRequests`))]); setMembers(memberDocs.docs.map((item) => item.data() as Member)); setRequests(requestDocs.docs.filter((item) => item.data().status === 'pending').map((item) => ({ id: item.id, ...item.data() } as AccessRequest))) }
  useEffect(() => { void refresh() }, [])
  async function manage(memberUid: string, action: string, houseId?: string) { try { await httpsCallable(firebaseServices().functions, 'manageMembership')({ batchId: PILOT_BATCH_ID, memberUid, action, houseId }); await refresh(); setNotice('Membership updated.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to update membership.') } }
  async function saveReunion(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); await setDoc(doc(firebaseServices().db, `batches/${PILOT_BATCH_ID}/reunion/config`), { title: values.get('title'), venue: values.get('venue'), instructions: values.get('instructions'), rsvpCutoffAt: new Date(String(values.get('cutoff'))), updatedAt: serverTimestamp() }, { merge: true }); setNotice('Reunion configuration saved.') }
  async function approve(requestId: string) { try { await httpsCallable(firebaseServices().functions, 'approveMembership')({ batchId: PILOT_BATCH_ID, requestId }); await refresh(); setNotice('Member approved.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to approve member.') } }
  return <section className="page-stack"><div><p className="eyebrow">Coordinator</p><h1>Batch operations</h1></div><section className="panel"><h2>Pending access requests</h2><div className="directory">{requests.map((request) => <div className="member-row" key={request.id}><span><strong>{request.displayName}</strong><small>{request.houseId ?? 'No house selected'}</small></span><button onClick={() => void approve(request.id)}>Approve</button></div>)}{!requests.length && <p className="muted">No pending requests.</p>}</div></section><form className="panel form-stack" onSubmit={saveReunion}><h2>Reunion details</h2><label>Title<input name="title" defaultValue="Silver Jubilee Reunion" required /></label><label>Venue<input name="venue" required /></label><label>RSVP cutoff<input name="cutoff" type="datetime-local" required /></label><label>Instructions<textarea name="instructions" maxLength={3000} /></label><button type="submit">Save reunion details</button></form><section className="panel"><h2>Membership management</h2><div className="directory">{members.map((member) => <div className="member-row" key={member.uid}><span><strong>{member.displayName ?? member.uid}</strong><small>{member.status} · {member.role ?? 'batchmate'}</small></span><span className="member-actions"><select aria-label={`House for ${member.uid}`} defaultValue={member.houseId ?? ''} onChange={(event) => void manage(member.uid, 'assignHouse', event.target.value)}><option value="" disabled>Assign house</option>{HOUSES.map((house) => <option key={house.id} value={house.id}>{house.name}</option>)}</select>{member.status === 'active' ? <button onClick={() => void manage(member.uid, 'suspend')}>Suspend</button> : <button onClick={() => void manage(member.uid, 'reinstate')}>Reinstate</button>}<button onClick={() => void manage(member.uid, 'remove')}>Remove</button><button onClick={() => void httpsCallable(firebaseServices().functions, 'reopenRsvp')({ batchId: PILOT_BATCH_ID, memberUid: member.uid })}>Reopen RSVP</button></span></div>)}</div></section>{notice && <p role="status">{notice}</p>}</section>
}
