import { FormEvent, useEffect, useRef, useState } from 'react'
import { collection, doc, DocumentData, getDoc, getDocs, limit, orderBy, query, QueryDocumentSnapshot, startAfter, where } from 'firebase/firestore/lite'
import { httpsCallable } from 'firebase/functions'
import { getBlob, ref, uploadBytes } from 'firebase/storage'
import { useAuth } from '../auth/AuthProvider'
import { firebaseServices } from '../lib/firebase'
import { paymentClaimPresentation, paymentClaimState, type PaymentClaimState } from '../lib/paymentClaim'
import { PILOT_BATCH_ID } from '../lib/membership'
import { PAGE_SIZE } from '../lib/pagination'

type Config = { upiId?: string; accountLabel?: string; defaultFamilyAmountPaise?: number; qrStoragePath?: string; contributionHeads?: string[] }
type Summary = { targetPaise?: number; collectedPaise?: number; expensePaise?: number; balancePaise?: number; verifiedFamilyCount?: number }
type Expense = { id: string; category: string; amountPaise: number; expenseDate?: { toDate: () => Date } }
type Claim = { id: string; amountPaise: number; contributionHead?: string; utr?: string; paymentDate?: { toDate: () => Date }; status: string; clarificationNote?: string; rejectionReason?: string }
const formatInr = (paise = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(paise / 100)

export function FinancePage() {
  const { user } = useAuth(); const requestId = useRef<string | null>(null)
  const [config, setConfig] = useState<Config>({}); const [summary, setSummary] = useState<Summary>({}); const [expenses, setExpenses] = useState<Expense[]>([]); const [claims, setClaims] = useState<Claim[]>([])
  const [expenseCursor, setExpenseCursor] = useState<QueryDocumentSnapshot<DocumentData>>(); const [hasMoreExpenses, setHasMoreExpenses] = useState(false); const [notice, setNotice] = useState(''); const [showQr, setShowQr] = useState(false); const [qrUrl, setQrUrl] = useState(''); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [correction, setCorrection] = useState<Claim | null>(null)
  const refresh = async () => {
    setLoading(true)
    try {
      const db = firebaseServices().db
      const [payment, fund, expenseDocs] = await Promise.all([getDoc(doc(db, `batches/${PILOT_BATCH_ID}/paymentConfig/current`)), getDoc(doc(db, `batches/${PILOT_BATCH_ID}/fundSummary/public`)), getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/expenses`), where('status', '==', 'approved'), orderBy('expenseDate', 'desc'), limit(PAGE_SIZE)))])
      const claimDocs = user ? await getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/paymentClaims`), where('memberUid', '==', user.uid), orderBy('submittedAt', 'desc'), limit(PAGE_SIZE))) : undefined
      setConfig(payment.data() ?? {}); setSummary(fund.data() ?? {}); setExpenses(expenseDocs.docs.map((item) => ({ id: item.id, ...item.data() } as Expense))); setExpenseCursor(expenseDocs.docs.at(-1)); setHasMoreExpenses(expenseDocs.size === PAGE_SIZE); setClaims(claimDocs?.docs.map((item) => ({ id: item.id, ...item.data() } as Claim)) ?? [])
    } catch { setNotice('Unable to load fund details. Reconnect and try again.') } finally { setLoading(false) }
  }
  useEffect(() => { void refresh() }, [user?.uid])
  useEffect(() => () => { if (qrUrl) URL.revokeObjectURL(qrUrl) }, [qrUrl])
  async function loadMoreExpenses() { if (!expenseCursor) return; try { const docs = await getDocs(query(collection(firebaseServices().db, `batches/${PILOT_BATCH_ID}/expenses`), where('status', '==', 'approved'), orderBy('expenseDate', 'desc'), startAfter(expenseCursor), limit(PAGE_SIZE))); setExpenses((current) => [...current, ...docs.docs.map((item) => ({ id: item.id, ...item.data() } as Expense))]); setExpenseCursor(docs.docs.at(-1)); setHasMoreExpenses(docs.size === PAGE_SIZE) } catch { setNotice('Unable to load more approved expenses.') } }
  async function openQr() { if (!config.qrStoragePath) return setNotice('The QR code will be added by a Coordinator.'); try { const blob = await getBlob(ref(firebaseServices().storage, config.qrStoragePath)); setQrUrl(URL.createObjectURL(blob)); setShowQr(true) } catch { setNotice('Unable to load the QR code.') } }
  async function copyUpi() { if (!config.upiId) return; try { await navigator.clipboard.writeText(config.upiId); setNotice('UPI ID copied.') } catch { setNotice('Unable to copy the UPI ID. Please copy it manually.') } }
  function openUpi() { if (!config.upiId) return setNotice('Payment instructions will be added by a Coordinator.'); window.location.assign(`upi://pay?pa=${encodeURIComponent(config.upiId)}&am=${((config.defaultFamilyAmountPaise ?? 0) / 100).toFixed(2)}&cu=INR`) }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const screenshot = form.get('screenshot') as File; setSubmitting(true)
    try {
      const amountPaise = Math.round(Number(form.get('amount')) * 100); const contributionHead = String(form.get('contributionHead')); const utr = String(form.get('utr')); const paymentDate = String(form.get('paymentDate'))
      if (correction) {
        let screenshotStoragePath: string | undefined
        if (screenshot?.size) { screenshotStoragePath = `batches/${PILOT_BATCH_ID}/payments/${correction.id}/evidence/${crypto.randomUUID()}-${screenshot.name}`; await uploadBytes(ref(firebaseServices().storage, screenshotStoragePath), screenshot) }
        await httpsCallable(firebaseServices().functions, 'resubmitPaymentClaim')({ batchId: PILOT_BATCH_ID, claimId: correction.id, amountPaise, utr, paymentDate, contributionHead, ...(screenshotStoragePath ? { screenshotStoragePath } : {}) }); setCorrection(null); setNotice('Corrected payment claim resubmitted for review.')
      } else {
        requestId.current ??= crypto.randomUUID()
        const result = await httpsCallable<Record<string, unknown>, { claimId: string; duplicate: boolean }>(firebaseServices().functions, 'submitPaymentClaim')({ batchId: PILOT_BATCH_ID, requestId: requestId.current, amountPaise, utr, paymentDate, contributionHead })
        if (screenshot?.size) { const path = `batches/${PILOT_BATCH_ID}/payments/${result.data.claimId}/evidence/${crypto.randomUUID()}-${screenshot.name}`; await uploadBytes(ref(firebaseServices().storage, path), screenshot); await httpsCallable(firebaseServices().functions, 'attachPaymentEvidence')({ batchId: PILOT_BATCH_ID, claimId: result.data.claimId, screenshotStoragePath: path }) }
        setNotice(result.data.duplicate ? 'Your original payment claim is already submitted.' : 'Payment claim submitted for Coordinator review.'); requestId.current = null
      }
      formElement.reset(); await refresh()
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to submit the payment claim. Your details remain available to retry.') } finally { setSubmitting(false) }
  }
  return <section className="page-stack"><div><p className="eyebrow">Reunion fund</p><h1>Transparent, together.</h1></div><section className="panel"><div className="finance-summary"><span><small>Collected</small><strong>{formatInr(summary.collectedPaise)}</strong></span><span><small>Expenses</small><strong>{formatInr(summary.expensePaise)}</strong></span><span><small>Balance</small><strong>{formatInr(summary.balancePaise)}</strong></span></div><p className="muted">{summary.verifiedFamilyCount ?? 0} verified contributing families · Target {formatInr(summary.targetPaise)}</p></section><section className="panel"><h2>Pay the reunion fund</h2><p className="muted">Pay directly to {config.accountLabel ?? 'the designated collection account'}. Never share a UPI PIN, password, or card details.</p><div className="member-actions"><button type="button" onClick={openUpi}>Open UPI app</button><button type="button" onClick={() => void copyUpi()} disabled={!config.upiId}>Copy UPI ID</button><button type="button" onClick={() => void openQr()}>Show QR</button></div>{showQr && qrUrl && <img className="payment-qr" src={qrUrl} alt="Coordinator UPI payment QR code" />}</section><ClaimForm config={config} correction={correction} onCancelCorrection={() => setCorrection(null)} onSubmit={submit} submitting={submitting} /><section className="panel"><h2>Your payment claims</h2>{loading ? <p className="muted">Loading your private claim status…</p> : claims.map((claim) => <ClaimStatus key={claim.id} claim={claim} onCorrect={() => setCorrection(claim)} />)}{!loading && !claims.length && <p className="muted">No payment claims yet.</p>}</section><section className="panel"><h2>Approved expenses</h2><div className="directory">{expenses.map((expense) => <div className="member-row" key={expense.id}><span><strong>{expense.category}</strong><small>{expense.expenseDate?.toDate().toLocaleDateString('en-IN') ?? 'Date pending'}</small></span><strong>{formatInr(expense.amountPaise)}</strong></div>)}{!expenses.length && <p className="muted">No approved expenses yet.</p>}</div>{hasMoreExpenses && <button type="button" onClick={() => void loadMoreExpenses()}>Load more expenses</button>}</section>{notice && <p role="status">{notice}</p>}</section>
}

function ClaimForm({ config, correction, onCancelCorrection, onSubmit, submitting }: { config: Config; correction: Claim | null; onCancelCorrection: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => Promise<void>; submitting: boolean }) { return <form className="panel form-stack" key={correction?.id ?? 'new'} onSubmit={(event) => void onSubmit(event)}><h2>{correction ? 'Correct payment claim' : 'Submit payment claim'}</h2><p className="muted">Your UTR and screenshot are visible only to Coordinators. {correction?.clarificationNote ?? correction?.rejectionReason ?? ''}</p><label>Contribution head<select name="contributionHead" defaultValue={correction?.contributionHead ?? config.contributionHeads?.[0]} required>{config.contributionHeads?.map((head) => <option key={head} value={head}>{head}</option>)}</select></label><label>Amount paid (₹)<input name="amount" type="number" min="1" step="0.01" defaultValue={correction ? correction.amountPaise / 100 : undefined} required /></label><label>UTR / transaction ID<input name="utr" maxLength={100} defaultValue={correction?.utr} required /></label><label>Payment date<input name="paymentDate" type="date" defaultValue={correction?.paymentDate?.toDate().toISOString().slice(0, 10)} required /></label><label>Screenshot (optional)<input name="screenshot" type="file" accept="image/jpeg,image/png,image/heic,image/webp" /></label><div className="member-actions"><button type="submit" disabled={submitting || !config.contributionHeads?.length}>{submitting ? 'Submitting…' : correction ? 'Resubmit corrected claim' : 'Submit for review'}</button>{correction && <button type="button" onClick={onCancelCorrection}>Cancel correction</button>}</div></form> }

function ClaimStatus({ claim, onCorrect }: { claim: Claim; onCorrect: () => void }) { const state = paymentClaimState(claim.status); const presentation = paymentClaimPresentation(state); return <div className="member-row"><span><strong>{claim.contributionHead ?? 'Contribution'} · {formatInr(claim.amountPaise)}</strong><small>{claim.paymentDate?.toDate().toLocaleDateString('en-IN') ?? 'Date pending'} · {claim.status.replaceAll(/([A-Z])/g, ' $1').toLowerCase()}</small><small>{presentation.copyKey === 'clarificationRequired' ? claim.clarificationNote : presentation.copyKey === 'rejected' ? claim.rejectionReason : claimCopy(state)}</small></span>{presentation.canResubmit && <button type="button" onClick={onCorrect}>Correct and resubmit</button>}</div> }
function claimCopy(state: PaymentClaimState) { return state === 'submitted' ? 'Submitted for Coordinator review.' : state === 'under_review' ? 'A Coordinator is reviewing this claim.' : state === 'verified' ? 'Verified.' : state === 'resubmitted' ? 'Corrected claim resubmitted.' : 'Ready to submit.' }
