import { FormEvent, useEffect, useRef, useState } from 'react'
import { collection, doc, DocumentData, getDoc, getDocs, limit, orderBy, query, QueryDocumentSnapshot, startAfter, where } from 'firebase/firestore/lite'
import { httpsCallable } from 'firebase/functions'
import { getBlob, ref, uploadBytesResumable, UploadTask } from 'firebase/storage'
import { useAuth } from '../auth/AuthProvider'
import { ARCHIVE_CATEGORIES, compressArchiveImage, matchesArchiveView, validateArchiveMedia } from '../lib/archive'
import type { ArchiveMedia, ArchiveView } from '../lib/archive'
import { firebaseServices } from '../lib/firebase'
import { reportTelemetry } from '../lib/telemetry'
import { PILOT_BATCH_ID } from '../lib/membership'
import { FormDialog } from '../app/FormDialog'
import { PAGE_SIZE } from '../lib/pagination'

type Media = ArchiveMedia & { thumbnailPath?: string; posterPath?: string; previewPath?: string }
type Post = { id: string; authorUid: string; caption?: string; media?: Media[]; peopleTags?: string[]; year?: number; category?: string; createdAt?: { toDate: () => Date } }
type Album = { id: string; authorUid: string; title: string; description?: string; media?: Media[] }
type Comment = { id: string; authorUid: string; body: string }
type Report = { id: string; targetType: string; targetId: string; category: string }
type PendingUpload = { file: File; duration?: number; path: string }
type ArchiveDialog = { kind: 'editPost'; post: Post; trigger: HTMLElement } | { kind: 'editAlbum'; album: Album; trigger: HTMLElement } | { kind: 'deletePost'; postId: string; trigger: HTMLElement } | { kind: 'deleteAlbum'; albumId: string; trigger: HTMLElement } | { kind: 'deleteComment'; postId: string; commentId: string; trigger: HTMLElement } | { kind: 'moderate'; reportId: string; action: 'hide' | 'remove'; trigger: HTMLElement }

async function videoDuration(file: File) {
  if (!file.type.startsWith('video/')) return undefined
  const url = URL.createObjectURL(file)
  try { return await new Promise<number>((resolve, reject) => { const video = document.createElement('video'); video.onloadedmetadata = () => resolve(video.duration); video.onerror = () => reject(new Error('The video could not be read.')); video.src = url }) } finally { URL.revokeObjectURL(url) }
}

export function MemoriesPage() {
  const { user, membership } = useAuth()
  const [view, setView] = useState<ArchiveView>('all'); const [posts, setPosts] = useState<Post[]>([]); const [albums, setAlbums] = useState<Album[]>([]); const [comments, setComments] = useState<Record<string, Comment[]>>({}); const [commentCursors, setCommentCursors] = useState<Record<string, QueryDocumentSnapshot<DocumentData> | undefined>>({}); const [hasMoreComments, setHasMoreComments] = useState<Record<string, boolean>>({}); const [liked, setLiked] = useState<Record<string, boolean>>({}); const [reports, setReports] = useState<Report[]>([]); const [cursors, setCursors] = useState<{ posts?: QueryDocumentSnapshot<DocumentData>; albums?: QueryDocumentSnapshot<DocumentData>; reports?: QueryDocumentSnapshot<DocumentData> }>({}); const [hasMore, setHasMore] = useState<{ posts?: boolean; albums?: boolean; reports?: boolean }>({}); const [notice, setNotice] = useState(''); const [progress, setProgress] = useState<number | null>(null); const [retry, setRetry] = useState<(() => void) | null>(null); const [dialog, setDialog] = useState<ArchiveDialog | null>(null)
  const upload = useRef<UploadTask | null>(null); const pendingPost = useRef<string | null>(null); const pendingPostRequestId = useRef<string | null>(null); const pendingUploads = useRef<PendingUpload[]>([])
  const refresh = async () => {
    const { db, auth } = firebaseServices()
    const [postDocs, albumDocs] = await Promise.all([getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/posts`), where('status', '==', 'visible'), orderBy('createdAt', 'desc'), limit(PAGE_SIZE))), getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/albums`), where('status', '==', 'visible'), orderBy('createdAt', 'desc'), limit(PAGE_SIZE)))])
    const nextPosts = postDocs.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Post)); setPosts(nextPosts); setAlbums(albumDocs.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Album)))
    const details = await Promise.all(nextPosts.map(async (post) => { const [commentDocs, likeDoc] = await Promise.all([getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/posts/${post.id}/comments`), where('status', '==', 'visible'), orderBy('createdAt', 'desc'), limit(PAGE_SIZE))), auth.currentUser ? getDoc(doc(db, `batches/${PILOT_BATCH_ID}/posts/${post.id}/likes/${auth.currentUser.uid}`)) : Promise.resolve(undefined)]); return [post.id, commentDocs.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Comment)), commentDocs.docs.at(-1), commentDocs.size === PAGE_SIZE, likeDoc?.exists() ?? false] as const }))
    setComments(Object.fromEntries(details.map(([id, list]) => [id, list]))); setCommentCursors(Object.fromEntries(details.map(([id, , cursor]) => [id, cursor]))); setHasMoreComments(Object.fromEntries(details.map(([id, , , hasMore]) => [id, hasMore]))); setLiked(Object.fromEntries(details.map(([id, , , , value]) => [id, value])))
    setCursors({ posts: postDocs.docs.at(-1), albums: albumDocs.docs.at(-1) }); setHasMore({ posts: postDocs.size === PAGE_SIZE, albums: albumDocs.size === PAGE_SIZE })
    if (membership?.role === 'coordinator') { const docs = await getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/reports`), where('status', '==', 'open'), orderBy('createdAt', 'desc'), limit(PAGE_SIZE))); setReports(docs.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Report))); setCursors((current) => ({ ...current, reports: docs.docs.at(-1) })); setHasMore((current) => ({ ...current, reports: docs.size === PAGE_SIZE })) }
  }
  useEffect(() => { void refresh().catch(() => setNotice('Unable to load the private archive.')); return () => { upload.current?.cancel() } }, [membership?.role])
  async function loadMore(kind: 'posts' | 'albums' | 'reports') { const cursor = cursors[kind]; if (!cursor) return; const db = firebaseServices().db; const collectionName = kind === 'posts' ? 'posts' : kind === 'albums' ? 'albums' : 'reports'; const docs = await getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/${collectionName}`), where('status', '==', kind === 'reports' ? 'open' : 'visible'), orderBy('createdAt', 'desc'), startAfter(cursor), limit(PAGE_SIZE))); if (kind === 'posts') setPosts((current) => [...current, ...docs.docs.map((item) => ({ id: item.id, ...item.data() } as Post))]); if (kind === 'albums') setAlbums((current) => [...current, ...docs.docs.map((item) => ({ id: item.id, ...item.data() } as Album))]); if (kind === 'reports') setReports((current) => [...current, ...docs.docs.map((item) => ({ id: item.id, ...item.data() } as Report))]); setCursors((current) => ({ ...current, [kind]: docs.docs.at(-1) })); setHasMore((current) => ({ ...current, [kind]: docs.size === PAGE_SIZE })) }
  async function loadMoreComments(postId: string) { const cursor = commentCursors[postId]; if (!cursor) return; const docs = await getDocs(query(collection(firebaseServices().db, `batches/${PILOT_BATCH_ID}/posts/${postId}/comments`), where('status', '==', 'visible'), orderBy('createdAt', 'desc'), startAfter(cursor), limit(PAGE_SIZE))); setComments((current) => ({ ...current, [postId]: [...(current[postId] ?? []), ...docs.docs.map((item) => ({ id: item.id, ...item.data() } as Comment))] })); setCommentCursors((current) => ({ ...current, [postId]: docs.docs.at(-1) })); setHasMoreComments((current) => ({ ...current, [postId]: docs.size === PAGE_SIZE })) }
  async function call(name: string, data: Record<string, unknown>, success: string) { try { await httpsCallable(firebaseServices().functions, name)({ batchId: PILOT_BATCH_ID, requestId: crypto.randomUUID(), ...data }); setNotice(success); await refresh(); return true } catch (error) { setNotice(error instanceof Error ? error.message : 'Archive action failed.'); return false } }
  async function publish(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const files = (form.getAll('media') as File[]).filter((file) => file.size)
    try {
      if (!pendingPost.current) {
        const selected = await Promise.all(files.map(async (file) => { const compressed = await compressArchiveImage(file); return { file: compressed, duration: await videoDuration(compressed) } })); selected.forEach(({ file, duration }) => validateArchiveMedia(file, duration))
        pendingPostRequestId.current ??= crypto.randomUUID()
        const post = await httpsCallable<Record<string, unknown>, { postId: string }>(firebaseServices().functions, 'createPost')({ batchId: PILOT_BATCH_ID, requestId: pendingPostRequestId.current, caption: form.get('caption'), albumId: form.get('albumId') || undefined, peopleTags: String(form.get('peopleTags') ?? '').split(',').map((tag) => tag.trim()).filter(Boolean), year: form.get('year') ? Number(form.get('year')) : undefined, category: form.get('category') || undefined, consentConfirmed: form.get('consent') === 'on' })
        pendingPost.current = post.data.postId; pendingUploads.current = selected.map(({ file, duration }) => ({ file, duration, path: `batches/${PILOT_BATCH_ID}/posts/${post.data.postId}/media/${crypto.randomUUID()}-${file.name}` }))
      }
      for (const item of [...pendingUploads.current]) { const task = uploadBytesResumable(ref(firebaseServices().storage, item.path), item.file, { contentType: item.file.type }); upload.current = task; await new Promise<void>((resolve, reject) => task.on('state_changed', (snap) => setProgress(Math.round(snap.bytesTransferred / snap.totalBytes * 100)), reject, resolve)); await httpsCallable(firebaseServices().functions, 'addArchiveMedia')({ batchId: PILOT_BATCH_ID, contentType: 'post', contentId: pendingPost.current, storagePath: item.path, mimeType: item.file.type, size: item.file.size, durationSeconds: item.duration }); pendingUploads.current = pendingUploads.current.filter((pending) => pending.path !== item.path) }
      pendingPost.current = null; pendingPostRequestId.current = null; formElement.reset(); setRetry(null); setNotice('Memory published to the private batch archive.'); await refresh()
    } catch (error) { void reportTelemetry({ eventCode: 'upload_failed', correlationId: crypto.randomUUID(), surface: 'archive' }); setRetry(() => () => void publish({ currentTarget: formElement, preventDefault() {} } as FormEvent<HTMLFormElement>)); setNotice(navigator.onLine ? (error instanceof Error ? error.message : 'Upload interrupted. Retry or cancel it.') : 'Upload paused while offline. Reconnect, then retry or cancel it.') } finally { upload.current = null; setProgress(null) }
  }
  async function submitDialog(values: FormData) {
    if (!dialog) return
    let success = false
    if (dialog.kind === 'editPost') success = await call('updateOwnPost', { postId: dialog.post.id, caption: values.get('caption'), peopleTags: dialog.post.peopleTags ?? [], year: dialog.post.year, category: dialog.post.category }, 'Memory updated.')
    if (dialog.kind === 'editAlbum') success = await call('manageAlbum', { albumId: dialog.album.id, action: 'update', title: values.get('title'), description: values.get('description') }, 'Album updated.')
    if (dialog.kind === 'deletePost') success = await call('deleteOwnPost', { postId: dialog.postId }, 'Your memory and its media were removed.')
    if (dialog.kind === 'deleteAlbum') success = await call('manageAlbum', { albumId: dialog.albumId, action: 'remove' }, 'Album removed and its media cleaned up.')
    if (dialog.kind === 'deleteComment') success = await call('deleteOwnComment', { postId: dialog.postId, commentId: dialog.commentId }, 'Comment removed.')
    if (dialog.kind === 'moderate') success = await call('moderateArchiveContent', { reportId: dialog.reportId, action: dialog.action }, dialog.action === 'hide' ? 'Content hidden.' : 'Content removed.')
    if (!success) throw new Error('Archive action failed. Please try again.')
    setDialog(null)
  }
  const filtered = view === 'albums' ? [] : posts.filter((post) => matchesArchiveView(post, view))
  return <section className="page-stack">
    <div><p className="eyebrow">Private archive</p><h1>Our memories.</h1></div>
    <div className="archive-tabs" role="tablist" aria-label="Archive views">{(['all', 'photos', 'videos', 'albums'] as ArchiveView[]).map((item) => <button key={item} role="tab" aria-selected={view === item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    <ArchiveForms albums={albums} progress={progress} onPublish={publish} onCancel={() => { upload.current?.cancel(); pendingPost.current = null; pendingPostRequestId.current = null; pendingUploads.current = []; setRetry(null); setNotice('Upload cancelled.') }} retry={retry} onCall={call} />
    {view === 'albums' ? <section className="archive-grid">{albums.map((album) => <article className="panel" key={album.id}><h2>{album.title}</h2>{album.description && <p>{album.description}</p>}<p className="muted">{album.media?.length ?? 0} items</p>{(album.authorUid === user?.uid || membership?.role === 'coordinator') && <span className="member-actions"><button onClick={(event) => setDialog({ kind: 'editAlbum', album, trigger: event.currentTarget })}>Edit album</button><button onClick={(event) => setDialog({ kind: 'deleteAlbum', albumId: album.id, trigger: event.currentTarget })}>Remove album</button></span>}</article>)}{hasMore.albums && <button type="button" onClick={() => void loadMore('albums')}>Load more albums</button>}</section> : <><Posts posts={filtered} comments={comments} hasMoreComments={hasMoreComments} liked={liked} userUid={user?.uid} onCall={call} onLoadMoreComments={loadMoreComments} onOpenDialog={setDialog} />{hasMore.posts && <button type="button" onClick={() => void loadMore('posts')}>Load more memories</button>}</>}
    {membership?.role === 'coordinator' && reports.length > 0 && <section className="panel"><h2>Open moderation reports</h2>{reports.map((report) => <div className="member-row" key={report.id}><span><strong>{report.category}</strong><small>{report.targetType} · {report.targetId}</small></span><span className="member-actions">{(['dismiss', 'hide', 'remove'] as const).map((action) => <button key={action} onClick={(event) => action === 'dismiss' ? void call('moderateArchiveContent', { reportId: report.id, action }, 'Report dismissed.') : setDialog({ kind: 'moderate', reportId: report.id, action, trigger: event.currentTarget })}>{action[0].toUpperCase() + action.slice(1)}</button>)}</span></div>)}{hasMore.reports && <button type="button" onClick={() => void loadMore('reports')}>Load more reports</button>}</section>}
    {notice && <p role="status">{notice}</p>}{dialog && <FormDialog title={dialog.kind === 'editPost' ? 'Edit memory' : dialog.kind === 'editAlbum' ? 'Edit album' : dialog.kind === 'deleteComment' ? 'Delete comment' : dialog.kind === 'deletePost' ? 'Delete memory' : dialog.kind === 'deleteAlbum' ? 'Remove album' : `${dialog.action === 'hide' ? 'Hide' : 'Remove'} reported content`} description={dialog.kind === 'editPost' ? 'Update the caption shown to approved batch members.' : dialog.kind === 'editAlbum' ? 'Update the album details shown to approved batch members.' : 'This action cannot be undone.'} submitLabel={dialog.kind === 'editPost' || dialog.kind === 'editAlbum' ? 'Save changes' : dialog.kind === 'deleteComment' ? 'Delete comment' : dialog.kind === 'deletePost' ? 'Delete memory' : dialog.kind === 'deleteAlbum' ? 'Remove album' : `${dialog.action === 'hide' ? 'Hide' : 'Remove'} content`} returnFocus={dialog.trigger} onClose={() => setDialog(null)} onSubmit={submitDialog}>{dialog.kind === 'editPost' && <label>Caption<textarea name="caption" defaultValue={dialog.post.caption} maxLength={2000} data-dialog-focus /></label>}{dialog.kind === 'editAlbum' && <><label>Album title<input name="title" defaultValue={dialog.album.title} maxLength={120} required data-dialog-focus /></label><label>Description<textarea name="description" defaultValue={dialog.album.description} maxLength={1000} /></label></>}</FormDialog>}
  </section>
}

function ArchiveForms({ albums, progress, onPublish, onCancel, retry, onCall }: { albums: Album[]; progress: number | null; onPublish: (event: FormEvent<HTMLFormElement>) => void; onCancel: () => void; retry: (() => void) | null; onCall: (name: string, data: Record<string, unknown>, success: string) => Promise<boolean> }) { return <><form className="panel form-stack" onSubmit={onPublish}><h2>Share a memory</h2><label>Caption<textarea name="caption" maxLength={2000} /></label><div className="field-row"><label>People tags (comma separated)<input name="peopleTags" maxLength={2000} /></label><label>Year<input name="year" type="number" min="1900" max={new Date().getFullYear()} /></label></div><div className="field-row"><label>Category<select name="category"><option value="">None</option>{ARCHIVE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Album<select name="albumId"><option value="">None</option>{albums.map((album) => <option key={album.id} value={album.id}>{album.title}</option>)}</select></label></div><label>Photos or videos<input name="media" type="file" multiple required accept="image/jpeg,image/png,image/heic,image/webp,video/mp4,video/quicktime" /></label><label className="check-label"><input name="consent" type="checkbox" required />I have the right to share this, it is suitable for this private batch, and it contains no sensitive financial or personal information without permission.</label><button>Publish memory</button>{progress !== null && <><progress value={progress} max="100">{progress}%</progress><button type="button" onClick={onCancel}>Cancel upload</button></>}{retry && <span className="member-actions"><button type="button" onClick={retry}>Retry upload</button><button type="button" onClick={onCancel}>Cancel upload</button></span>}</form><form className="panel form-stack" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onCall('createAlbum', { title: form.get('title'), description: form.get('description'), consentConfirmed: form.get('consent') === 'on' }, 'Album created.'); event.currentTarget.reset() }}><h2>Create an album</h2><label>Title<input name="title" maxLength={120} required /></label><label>Description<textarea name="description" maxLength={1000} /></label><label className="check-label"><input name="consent" type="checkbox" required />I have the right to share this album with approved batch members.</label><button>Create album</button></form></> }

function Posts({ posts, comments, hasMoreComments, liked, userUid, onCall, onLoadMoreComments, onOpenDialog }: { posts: Post[]; comments: Record<string, Comment[]>; hasMoreComments: Record<string, boolean>; liked: Record<string, boolean>; userUid?: string; onCall: (name: string, data: Record<string, unknown>, success: string) => Promise<boolean>; onLoadMoreComments: (postId: string) => Promise<void>; onOpenDialog: (dialog: ArchiveDialog) => void }) { return <section className="page-stack">{posts.map((post) => <article className="panel" key={post.id}><div className="member-row"><span><strong>{post.authorUid}</strong><small>{post.createdAt?.toDate().toLocaleString('en-IN') ?? 'Just now'}</small></span><span className="member-actions"><button onClick={() => void onCall('reportArchiveContent', { targetType: 'post', targetId: post.id, category: 'other' }, 'Report sent privately to Coordinators.')}>Report</button>{post.authorUid === userUid && <><button onClick={(event) => onOpenDialog({ kind: 'editPost', post, trigger: event.currentTarget })}>Edit</button><button onClick={(event) => onOpenDialog({ kind: 'deletePost', postId: post.id, trigger: event.currentTarget })}>Delete</button></>}</span></div>{post.caption && <p>{post.caption}</p>}{(post.peopleTags?.length || post.year || post.category) && <p className="muted">{[post.peopleTags?.join(', '), post.year, post.category].filter(Boolean).join(' · ')}</p>}<div className="archive-media">{post.media?.map((media) => <ArchiveMedia key={media.path} media={media} />)}</div><button onClick={() => void onCall('setArchiveLike', { postId: post.id, liked: !liked[post.id] }, liked[post.id] ? 'Like removed.' : 'Liked.')}>{liked[post.id] ? 'Unlike' : 'Like'}</button><div className="comments">{comments[post.id]?.map((comment) => <p key={comment.id}><strong>{comment.authorUid}</strong> · {comment.body}{comment.authorUid === userUid && <button className="text-button" onClick={(event) => onOpenDialog({ kind: 'deleteComment', postId: post.id, commentId: comment.id, trigger: event.currentTarget })}>Delete</button>}</p>)}</div>{hasMoreComments[post.id] && <button type="button" onClick={() => void onLoadMoreComments(post.id)}>Load more comments</button>}<form className="comment-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onCall('saveArchiveComment', { postId: post.id, body: form.get('body') }, 'Comment added.'); event.currentTarget.reset() }}><input name="body" maxLength={1000} required aria-label="Comment" placeholder="Add a comment" /><button>Comment</button></form></article>)}{!posts.length && <section className="panel"><p className="muted">No memories in this view yet.</p></section>}</section> }

function ArchiveMedia({ media }: { media: Media }) { const [source, setSource] = useState(''); const [poster, setPoster] = useState(''); useEffect(() => { let active = true; const urls: string[] = []; const load = async (path: string) => { const url = URL.createObjectURL(await getBlob(ref(firebaseServices().storage, path))); urls.push(url); return url }; void Promise.all([load(media.mimeType.startsWith('image/') ? media.thumbnailPath ?? media.path : media.previewPath ?? media.path), media.posterPath ? load(media.posterPath) : Promise.resolve('')]).then(([nextSource, nextPoster]) => { if (active) { setSource(nextSource); setPoster(nextPoster) } }).catch(() => setSource('')); return () => { active = false; urls.forEach(URL.revokeObjectURL) } }, [media.path, media.thumbnailPath, media.posterPath, media.previewPath]); if (!source) return null; return media.mimeType.startsWith('video/') ? <video controls poster={poster || undefined} src={source} /> : <img src={source} alt="Shared batch memory" /> }
