import { FormEvent, useEffect, useRef, useState } from 'react'
import { collection, getDocs, orderBy, query, where } from 'firebase/firestore/lite'
import { httpsCallable } from 'firebase/functions'
import { getBlob, ref, uploadBytesResumable, UploadTask } from 'firebase/storage'
import { useAuth } from '../auth/AuthProvider'
import { ARCHIVE_CATEGORIES, matchesArchiveView, validateArchiveMedia } from '../lib/archive'
import type { ArchiveMedia, ArchiveView } from '../lib/archive'
import { firebaseServices } from '../lib/firebase'
import { PILOT_BATCH_ID } from '../lib/membership'

type Media = ArchiveMedia & { thumbnailPath?: string; posterPath?: string; previewPath?: string }
type Post = { id: string; authorUid: string; caption?: string; media?: Media[]; peopleTags?: string[]; year?: number; category?: string; createdAt?: { toDate: () => Date } }
type Album = { id: string; authorUid: string; title: string; description?: string; media?: Media[] }
type Comment = { id: string; authorUid: string; body: string }
type Report = { id: string; targetType: string; targetId: string; category: string }
type PendingUpload = { file: File; duration?: number; path: string }

async function videoDuration(file: File) {
  if (!file.type.startsWith('video/')) return undefined
  const url = URL.createObjectURL(file)
  try { return await new Promise<number>((resolve, reject) => { const video = document.createElement('video'); video.onloadedmetadata = () => resolve(video.duration); video.onerror = () => reject(new Error('The video could not be read.')); video.src = url }) } finally { URL.revokeObjectURL(url) }
}

export function MemoriesPage() {
  const { user, membership } = useAuth()
  const [view, setView] = useState<ArchiveView>('all'); const [posts, setPosts] = useState<Post[]>([]); const [albums, setAlbums] = useState<Album[]>([]); const [comments, setComments] = useState<Record<string, Comment[]>>({}); const [liked, setLiked] = useState<Record<string, boolean>>({}); const [reports, setReports] = useState<Report[]>([]); const [notice, setNotice] = useState(''); const [progress, setProgress] = useState<number | null>(null); const [retry, setRetry] = useState<(() => void) | null>(null)
  const upload = useRef<UploadTask | null>(null); const pendingPost = useRef<string | null>(null); const pendingUploads = useRef<PendingUpload[]>([])
  const refresh = async () => {
    const { db, auth } = firebaseServices()
    const [postDocs, albumDocs] = await Promise.all([getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/posts`), where('status', '==', 'visible'), orderBy('createdAt', 'desc'))), getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/albums`), where('status', '==', 'visible')))])
    const nextPosts = postDocs.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Post)); setPosts(nextPosts); setAlbums(albumDocs.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Album)))
    const details = await Promise.all(nextPosts.map(async (post) => { const [commentDocs, likeDocs] = await Promise.all([getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/posts/${post.id}/comments`), where('status', '==', 'visible'))), getDocs(collection(db, `batches/${PILOT_BATCH_ID}/posts/${post.id}/likes`))]); return [post.id, commentDocs.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Comment)), likeDocs.docs.some((doc) => doc.id === auth.currentUser?.uid)] as const }))
    setComments(Object.fromEntries(details.map(([id, list]) => [id, list]))); setLiked(Object.fromEntries(details.map(([id, , value]) => [id, value])))
    if (membership?.role === 'coordinator') { const docs = await getDocs(collection(db, `batches/${PILOT_BATCH_ID}/reports`)); setReports(docs.docs.filter((doc) => doc.data().status === 'open').map((doc) => ({ id: doc.id, ...doc.data() } as Report))) }
  }
  useEffect(() => { void refresh().catch(() => setNotice('Unable to load the private archive.')); return () => { upload.current?.cancel() } }, [membership?.role])
  async function call(name: string, data: Record<string, unknown>, success: string) { try { await httpsCallable(firebaseServices().functions, name)({ batchId: PILOT_BATCH_ID, ...data }); setNotice(success); await refresh() } catch (error) { setNotice(error instanceof Error ? error.message : 'Archive action failed.') } }
  async function publish(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const files = (form.getAll('media') as File[]).filter((file) => file.size)
    try {
      if (!pendingPost.current) {
        const selected = await Promise.all(files.map(async (file) => ({ file, duration: await videoDuration(file) }))); selected.forEach(({ file, duration }) => validateArchiveMedia(file, duration))
        const post = await httpsCallable<Record<string, unknown>, { postId: string }>(firebaseServices().functions, 'createPost')({ batchId: PILOT_BATCH_ID, caption: form.get('caption'), albumId: form.get('albumId') || undefined, peopleTags: String(form.get('peopleTags') ?? '').split(',').map((tag) => tag.trim()).filter(Boolean), year: form.get('year') ? Number(form.get('year')) : undefined, category: form.get('category') || undefined, consentConfirmed: form.get('consent') === 'on' })
        pendingPost.current = post.data.postId; pendingUploads.current = selected.map(({ file, duration }) => ({ file, duration, path: `batches/${PILOT_BATCH_ID}/posts/${post.data.postId}/media/${crypto.randomUUID()}-${file.name}` }))
      }
      for (const item of [...pendingUploads.current]) { const task = uploadBytesResumable(ref(firebaseServices().storage, item.path), item.file, { contentType: item.file.type }); upload.current = task; await new Promise<void>((resolve, reject) => task.on('state_changed', (snap) => setProgress(Math.round(snap.bytesTransferred / snap.totalBytes * 100)), reject, resolve)); await httpsCallable(firebaseServices().functions, 'addArchiveMedia')({ batchId: PILOT_BATCH_ID, contentType: 'post', contentId: pendingPost.current, storagePath: item.path, mimeType: item.file.type, size: item.file.size, durationSeconds: item.duration }); pendingUploads.current = pendingUploads.current.filter((pending) => pending.path !== item.path) }
      pendingPost.current = null; formElement.reset(); setRetry(null); setNotice('Memory published to the private batch archive.'); await refresh()
    } catch (error) { setRetry(() => () => void publish({ currentTarget: formElement, preventDefault() {} } as FormEvent<HTMLFormElement>)); setNotice(navigator.onLine ? (error instanceof Error ? error.message : 'Upload interrupted. Retry or cancel it.') : 'Upload paused while offline. Reconnect, then retry or cancel it.') } finally { upload.current = null; setProgress(null) }
  }
  const editPost = (post: Post) => { const caption = window.prompt('Caption', post.caption ?? ''); if (caption !== null) void call('updateOwnPost', { postId: post.id, caption, peopleTags: post.peopleTags ?? [], year: post.year, category: post.category }, 'Memory updated.') }
  const editAlbum = (album: Album) => { const title = window.prompt('Album title', album.title); if (title === null) return; const description = window.prompt('Album description', album.description ?? ''); if (description !== null) void call('manageAlbum', { albumId: album.id, action: 'update', title, description }, 'Album updated.') }
  const filtered = view === 'albums' ? [] : posts.filter((post) => matchesArchiveView(post, view))
  return <section className="page-stack">
    <div><p className="eyebrow">Private archive</p><h1>Our memories.</h1></div>
    <div className="archive-tabs" role="tablist" aria-label="Archive views">{(['all', 'photos', 'videos', 'albums'] as ArchiveView[]).map((item) => <button key={item} role="tab" aria-selected={view === item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    <ArchiveForms albums={albums} progress={progress} onPublish={publish} onCancel={() => { upload.current?.cancel(); pendingPost.current = null; pendingUploads.current = []; setRetry(null); setNotice('Upload cancelled.') }} retry={retry} onCall={call} />
    {view === 'albums' ? <section className="archive-grid">{albums.map((album) => <article className="panel" key={album.id}><h2>{album.title}</h2>{album.description && <p>{album.description}</p>}<p className="muted">{album.media?.length ?? 0} items</p>{(album.authorUid === user?.uid || membership?.role === 'coordinator') && <span className="member-actions"><button onClick={() => editAlbum(album)}>Edit album</button><button onClick={() => void call('manageAlbum', { albumId: album.id, action: 'remove' }, 'Album removed and its media cleaned up.')}>Remove album</button></span>}</article>)}</section> : <Posts posts={filtered} comments={comments} liked={liked} userUid={user?.uid} onCall={call} onEdit={editPost} />}
    {membership?.role === 'coordinator' && reports.length > 0 && <section className="panel"><h2>Open moderation reports</h2>{reports.map((report) => <div className="member-row" key={report.id}><span><strong>{report.category}</strong><small>{report.targetType} · {report.targetId}</small></span><span className="member-actions">{['dismiss', 'hide', 'remove'].map((action) => <button key={action} onClick={() => void call('moderateArchiveContent', { reportId: report.id, action }, action === 'hide' ? 'Content hidden.' : action === 'remove' ? 'Content removed.' : 'Report dismissed.')}>{action[0].toUpperCase() + action.slice(1)}</button>)}</span></div>)}</section>}
    {notice && <p role="status">{notice}</p>}
  </section>
}

function ArchiveForms({ albums, progress, onPublish, onCancel, retry, onCall }: { albums: Album[]; progress: number | null; onPublish: (event: FormEvent<HTMLFormElement>) => void; onCancel: () => void; retry: (() => void) | null; onCall: (name: string, data: Record<string, unknown>, success: string) => Promise<void> }) { return <><form className="panel form-stack" onSubmit={onPublish}><h2>Share a memory</h2><label>Caption<textarea name="caption" maxLength={2000} /></label><div className="field-row"><label>People tags (comma separated)<input name="peopleTags" maxLength={2000} /></label><label>Year<input name="year" type="number" min="1900" max={new Date().getFullYear()} /></label></div><div className="field-row"><label>Category<select name="category"><option value="">None</option>{ARCHIVE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Album<select name="albumId"><option value="">None</option>{albums.map((album) => <option key={album.id} value={album.id}>{album.title}</option>)}</select></label></div><label>Photos or videos<input name="media" type="file" multiple required accept="image/jpeg,image/png,image/heic,image/webp,video/mp4,video/quicktime" /></label><label className="check-label"><input name="consent" type="checkbox" required />I have the right to share this, it is suitable for this private batch, and it contains no sensitive financial or personal information without permission.</label><button>Publish memory</button>{progress !== null && <><progress value={progress} max="100">{progress}%</progress><button type="button" onClick={onCancel}>Cancel upload</button></>}{retry && <span className="member-actions"><button type="button" onClick={retry}>Retry upload</button><button type="button" onClick={onCancel}>Cancel upload</button></span>}</form><form className="panel form-stack" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onCall('createAlbum', { title: form.get('title'), description: form.get('description'), consentConfirmed: form.get('consent') === 'on' }, 'Album created.'); event.currentTarget.reset() }}><h2>Create an album</h2><label>Title<input name="title" maxLength={120} required /></label><label>Description<textarea name="description" maxLength={1000} /></label><label className="check-label"><input name="consent" type="checkbox" required />I have the right to share this album with approved batch members.</label><button>Create album</button></form></> }

function Posts({ posts, comments, liked, userUid, onCall, onEdit }: { posts: Post[]; comments: Record<string, Comment[]>; liked: Record<string, boolean>; userUid?: string; onCall: (name: string, data: Record<string, unknown>, success: string) => Promise<void>; onEdit: (post: Post) => void }) { return <section className="page-stack">{posts.map((post) => <article className="panel" key={post.id}><div className="member-row"><span><strong>{post.authorUid}</strong><small>{post.createdAt?.toDate().toLocaleString('en-IN') ?? 'Just now'}</small></span><span className="member-actions"><button onClick={() => void onCall('reportArchiveContent', { targetType: 'post', targetId: post.id, category: 'other' }, 'Report sent privately to Coordinators.')}>Report</button>{post.authorUid === userUid && <><button onClick={() => onEdit(post)}>Edit</button><button onClick={() => void onCall('deleteOwnPost', { postId: post.id }, 'Your memory and its media were removed.')}>Delete</button></>}</span></div>{post.caption && <p>{post.caption}</p>}{(post.peopleTags?.length || post.year || post.category) && <p className="muted">{[post.peopleTags?.join(', '), post.year, post.category].filter(Boolean).join(' · ')}</p>}<div className="archive-media">{post.media?.map((media) => <ArchiveMedia key={media.path} media={media} />)}</div><button onClick={() => void onCall('setArchiveLike', { postId: post.id, liked: !liked[post.id] }, liked[post.id] ? 'Like removed.' : 'Liked.')}>{liked[post.id] ? 'Unlike' : 'Like'}</button><div className="comments">{comments[post.id]?.map((comment) => <p key={comment.id}><strong>{comment.authorUid}</strong> · {comment.body}{comment.authorUid === userUid && <button className="text-button" onClick={() => void onCall('deleteOwnComment', { postId: post.id, commentId: comment.id }, 'Comment removed.')}>Delete</button>}</p>)}</div><form className="comment-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onCall('saveArchiveComment', { postId: post.id, body: form.get('body') }, 'Comment added.'); event.currentTarget.reset() }}><input name="body" maxLength={1000} required aria-label="Comment" placeholder="Add a comment" /><button>Comment</button></form></article>)}{!posts.length && <section className="panel"><p className="muted">No memories in this view yet.</p></section>}</section> }

function ArchiveMedia({ media }: { media: Media }) { const [source, setSource] = useState(''); const [poster, setPoster] = useState(''); useEffect(() => { let active = true; const urls: string[] = []; const load = async (path: string) => { const url = URL.createObjectURL(await getBlob(ref(firebaseServices().storage, path))); urls.push(url); return url }; void Promise.all([load(media.mimeType.startsWith('image/') ? media.thumbnailPath ?? media.path : media.previewPath ?? media.path), media.posterPath ? load(media.posterPath) : Promise.resolve('')]).then(([nextSource, nextPoster]) => { if (active) { setSource(nextSource); setPoster(nextPoster) } }).catch(() => setSource('')); return () => { active = false; urls.forEach(URL.revokeObjectURL) } }, [media.path, media.thumbnailPath, media.posterPath, media.previewPath]); if (!source) return null; return media.mimeType.startsWith('video/') ? <video controls poster={poster || undefined} src={source} /> : <img src={source} alt="Shared batch memory" /> }
