import { FormEvent, useEffect, useState } from 'react'
import { collection, doc, getDoc, getDocs, limit, orderBy, query, serverTimestamp, setDoc, where } from 'firebase/firestore/lite'
import { httpsCallable } from 'firebase/functions'
import { ref, uploadBytes } from 'firebase/storage'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { firebaseServices } from '../lib/firebase'
import { PILOT_BATCH_ID } from '../lib/membership'
import { applyTheme, hasProfileChanges, loadTheme, profileValues, ThemePreference, themeOptions, type MemberProfile } from '../lib/profile'
import { COPY } from '../lib/copy'
import { Avatar, ErrorState, Skeleton } from '../ui/Primitives'
import { FormDialog } from '../app/FormDialog'
import { canAccessCoordinatorTools } from './navigation'

export function ProfilePage() {
  const { user, membership } = useAuth(); const [profile, setProfile] = useState<Partial<MemberProfile>>({}); const [posts, setPosts] = useState(0); const [theme, setTheme] = useState<ThemePreference>(loadTheme()); const [notice, setNotice] = useState(''); const [dirty, setDirty] = useState(false); const [preview, setPreview] = useState(false)
  useEffect(() => { if (!user) return; const db = firebaseServices().db; void getDoc(doc(db, `batches/${PILOT_BATCH_ID}/profiles/${user.uid}`)).then((snapshot) => setProfile(snapshot.data() ?? {})); void getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/posts`), where('authorUid', '==', user.uid), orderBy('createdAt', 'desc'), limit(25))).then((ownPosts) => setPosts(ownPosts.size)).catch(() => setPosts(0)) }, [user])
  function markDirty(event: FormEvent<HTMLFormElement>) { const form = new FormData(event.currentTarget); const raw = Object.fromEntries(form); const input: Record<string, string> = {}; Object.keys(raw).forEach((key) => { input[key] = String(raw[key] ?? '') }); setDirty(hasProfileChanges(profile, input)) }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) return; try { const form = new FormData(event.currentTarget); const next = profileValues(Object.fromEntries(form)); const avatar = form.get('avatar') as File; let avatarPath: string | undefined = profile.avatarPath; if (avatar?.size) { if (!avatar.type.match(/^image\/(jpeg|png|heic|webp)$/) || avatar.size > 20 * 1024 * 1024) throw new Error('Choose a JPG, PNG, HEIC, or WebP image up to 20 MB.'); avatarPath = `batches/${PILOT_BATCH_ID}/profiles/${user.uid}/avatar/${Date.now()}-${avatar.name}`; await uploadBytes(ref(firebaseServices().storage, avatarPath), avatar) } const saved = { ...next, avatarPath, houseId: profile.houseId }; await setDoc(doc(firebaseServices().db, `batches/${PILOT_BATCH_ID}/profiles/${user.uid}`), { uid: user.uid, ...next, ...(avatarPath ? { avatarPath } : {}), updatedAt: serverTimestamp() }, { merge: true }); setProfile(saved); setDirty(false); setNotice(COPY.account.saved) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to save profile.') } }
  async function requestData(action: 'correction' | 'deletion') { try { await httpsCallable(firebaseServices().functions, 'requestProfileDataChange')({ batchId: PILOT_BATCH_ID, action, requestId: crypto.randomUUID() }); setNotice(`Your ${action} request was sent to the Coordinators.`) } catch { setNotice('Unable to send your request.') } }
  const [confirmDelete, setConfirmDelete] = useState(false)
  return <section className="page-stack"><div><p className="eyebrow">{COPY.account.eyebrow}</p><h1>{COPY.account.title}</h1><p className="muted">{COPY.account.intro}</p></div>{dirty && <p className="surface-warning connection-notice" role="status">{COPY.account.unsaved}</p>}
    {preview ? <ProfilePreview profile={profile} onBack={() => setPreview(false)} /> : <form className="panel form-stack" key={JSON.stringify(profile)} onSubmit={save} onChange={markDirty}>
      <fieldset><legend>{COPY.account.identity}</legend><p className="muted">{COPY.account.identityHint}</p><label>Name<input name="displayName" defaultValue={profile.displayName} maxLength={100} required /></label><label>City<input name="city" defaultValue={profile.city} maxLength={100} /></label><label>Avatar (optional)<input name="avatar" type="file" accept="image/jpeg,image/png,image/heic,image/webp" /></label></fieldset>
      <fieldset><legend>{COPY.account.life}</legend><label>Profession<input name="profession" defaultValue={profile.profession} maxLength={100} /></label><label>About<textarea name="about" defaultValue={profile.about} maxLength={500} /></label></fieldset>
      <fieldset><legend>{COPY.account.schoolMemories}</legend><label>Favourite school memory<textarea name="favouriteSchoolMemory" defaultValue={profile.favouriteSchoolMemory} maxLength={500} /></label><label>Favourite teacher or activity<input name="teacherOrActivity" defaultValue={profile.teacherOrActivity} maxLength={150} /></label></fieldset>
      <fieldset><legend>{COPY.account.links}</legend><label>LinkedIn (optional)<input name="linkedin" type="url" defaultValue={profile.socialLinks?.linkedin} /></label><label>Instagram (optional)<input name="instagram" type="url" defaultValue={profile.socialLinks?.instagram} /></label><label>Website (optional)<input name="website" type="url" defaultValue={profile.socialLinks?.website} /></label></fieldset>
      {dirty && <div className="sticky-save"><span className="muted">{COPY.account.unsaved}</span><div className="member-actions"><Link className="text-button" to="#" onClick={(event) => { event.preventDefault(); setPreview(true) }}>{COPY.account.preview}</Link><button type="submit">{COPY.account.save}</button></div></div>}
    </form>}
    <section className="panel"><h2>{COPY.account.memoriesLabel}</h2><p className="muted">{COPY.account.memoriesCount(posts)}</p><Link className="text-link" to="/memories">{COPY.account.viewMemories}</Link></section>
    <section className="panel form-stack"><h2>{COPY.account.appearance}</h2><label>{COPY.account.themeLabel}<select value={theme} onChange={(event) => { const next = event.target.value as ThemePreference; setTheme(next); applyTheme(next) }}>{themeOptions.map((option) => <option key={option} value={option}>{option[0].toUpperCase() + option.slice(1)}</option>)}</select></label></section>
    <section className="panel"><h2>{COPY.account.privacySupport}</h2><p className="muted">{COPY.account.privacyBody}</p><div className="member-actions"><button onClick={() => void requestData('correction')}>{COPY.account.requestCorrection}</button><button onClick={() => void requestData('deletion')}>{COPY.account.requestDeletion}</button><a className="text-link" href="https://wa.me/" target="_blank" rel="noreferrer">{COPY.account.contactCoordinator}</a></div></section>
    <section className="panel"><h2>{COPY.account.danger}</h2><p className="muted">{COPY.account.dangerHint}</p><button className="ui-button ui-button--danger" onClick={() => setConfirmDelete(true)}>{COPY.account.requestDeletion}</button></section>
    {canAccessCoordinatorTools(membership?.role) && <section className="panel"><h2>{COPY.account.coordinatorTools}</h2><Link className="text-link" to="/account/coordinator">{COPY.account.openCoordinatorTools}</Link></section>}
    {notice && <p role="status">{notice}</p>}
    {confirmDelete && <FormDialog title="Delete profile data" description="This sends a deletion request to the Coordinators. Your data remains behind the existing approval process and is not lost locally." submitLabel="Send deletion request" returnFocus={null} onClose={() => setConfirmDelete(false)} onSubmit={async () => { await requestData('deletion'); return }} />}
  </section>
}

function ProfilePreview({ profile, onBack }: { profile: Partial<MemberProfile>; onBack: () => void }) {
  return <article className="panel"><p className="eyebrow">{COPY.directory.profileVisibility}</p><div className="member-row"><Avatar name={profile.displayName ?? ''} /><span><h1>{profile.displayName}</h1><p className="muted">{[profile.city, profile.profession].filter(Boolean).join(' · ')}</p></span></div>{profile.about && <p>{profile.about}</p>}{profile.favouriteSchoolMemory && <p><strong>Favourite memory:</strong> {profile.favouriteSchoolMemory}</p>}{profile.teacherOrActivity && <p><strong>Teacher or activity:</strong> {profile.teacherOrActivity}</p>}<div className="member-actions"><button type="button" onClick={onBack}>Back to edit</button></div></article>
}

export function MemberProfilePage() {
  const { uid = '' } = useParams(); const { user } = useAuth(); const [profile, setProfile] = useState<MemberProfile | null>(); const [notice, setNotice] = useState(''); const [failed, setFailed] = useState(false)
  async function load() { setProfile(undefined); setFailed(false); try { const snapshot = await getDoc(doc(firebaseServices().db, `batches/${PILOT_BATCH_ID}/profiles/${uid}`)); setProfile(snapshot.data() as MemberProfile ?? null) } catch { setFailed(true); setProfile(null) } }
  useEffect(() => { void load() }, [uid])
  async function report() { try { await httpsCallable(firebaseServices().functions, 'reportArchiveContent')({ batchId: PILOT_BATCH_ID, targetType: 'profile', targetId: uid, category: 'privacy', requestId: crypto.randomUUID() }); setNotice(COPY.directory.reportSent) } catch { setNotice(COPY.directory.reportFailed) } }
  if (profile === undefined) return <section className="page-stack"><Skeleton label={COPY.directory.loading} /></section>
  if (!profile || failed) return <section className="page-stack"><ErrorState title={COPY.directory.profileUnavailable} retry={<button onClick={() => void load()}>{COPY.directory.retry}</button>} /></section>
  return <section className="page-stack"><Link className="text-link" to="/houses">{COPY.directory.profileBack}</Link><article className="panel"><p className="eyebrow">{COPY.directory.profileVisibility}</p><div className="member-row"><Avatar name={profile.displayName} /><span><h1>{profile.displayName}</h1><p className="muted">{[profile.city, profile.profession].filter(Boolean).join(' · ')}</p></span></div>{profile.about && <p>{profile.about}</p>}{profile.favouriteSchoolMemory && <p><strong>Favourite memory:</strong> {profile.favouriteSchoolMemory}</p>}{profile.teacherOrActivity && <p><strong>Teacher or activity:</strong> {profile.teacherOrActivity}</p>}<div className="member-actions">{Object.values(profile.socialLinks ?? {}).map((link) => <a key={link} className="text-link" href={link} target="_blank" rel="noreferrer">Social link</a>)}{user?.uid !== uid && <button onClick={() => void report()}>{COPY.directory.reportProfile}</button>}</div>{notice && <p role="status">{notice}</p>}</article></section>
}
