import { FormEvent, useEffect, useState } from 'react'
import { collection, doc, getDoc, getDocs, limit, orderBy, query, serverTimestamp, setDoc, where } from 'firebase/firestore/lite'
import { httpsCallable } from 'firebase/functions'
import { ref, uploadBytes } from 'firebase/storage'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { firebaseServices } from '../lib/firebase'
import { PILOT_BATCH_ID } from '../lib/membership'
import { applyTheme, loadTheme, profileValues, ThemePreference, themeOptions, type MemberProfile } from '../lib/profile'
import { canAccessCoordinatorTools } from './navigation'

export function ProfilePage() {
  const { user, membership } = useAuth(); const [profile, setProfile] = useState<Partial<MemberProfile>>({}); const [posts, setPosts] = useState(0); const [theme, setTheme] = useState<ThemePreference>(loadTheme()); const [notice, setNotice] = useState('')
  useEffect(() => { if (!user) return; const db = firebaseServices().db; void getDoc(doc(db, `batches/${PILOT_BATCH_ID}/profiles/${user.uid}`)).then((snapshot) => setProfile(snapshot.data() ?? {})); void getDocs(query(collection(db, `batches/${PILOT_BATCH_ID}/posts`), where('authorUid', '==', user.uid), orderBy('createdAt', 'desc'), limit(25))).then((ownPosts) => setPosts(ownPosts.size)).catch(() => setPosts(0)) }, [user])
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) return; try { const form = new FormData(event.currentTarget); const next = profileValues(Object.fromEntries(form)); const avatar = form.get('avatar') as File; let avatarPath = profile.avatarPath; if (avatar?.size) { if (!avatar.type.match(/^image\/(jpeg|png|heic|webp)$/) || avatar.size > 20 * 1024 * 1024) throw new Error('Choose a JPG, PNG, HEIC, or WebP image up to 20 MB.'); avatarPath = `batches/${PILOT_BATCH_ID}/profiles/${user.uid}/avatar/${Date.now()}-${avatar.name}`; await uploadBytes(ref(firebaseServices().storage, avatarPath), avatar) } await setDoc(doc(firebaseServices().db, `batches/${PILOT_BATCH_ID}/profiles/${user.uid}`), { uid: user.uid, ...next, ...(avatarPath ? { avatarPath } : {}), updatedAt: serverTimestamp() }, { merge: true }); setProfile({ ...next, avatarPath }); setNotice('Profile saved.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to save profile.') } }
  async function requestData(action: 'correction' | 'deletion') { try { await httpsCallable(firebaseServices().functions, 'requestProfileDataChange')({ batchId: PILOT_BATCH_ID, action, requestId: crypto.randomUUID() }); setNotice(`Your ${action} request was sent to the Coordinators.`) } catch { setNotice('Unable to send your request.') } }
  return <section className="page-stack"><div><p className="eyebrow">Account</p><h1>Your profile</h1><p className="muted">Visible only to approved batch members.</p></div><form className="panel form-stack" key={JSON.stringify(profile)} onSubmit={save}><label>Name<input name="displayName" defaultValue={profile.displayName} maxLength={100} required /></label><label>City<input name="city" defaultValue={profile.city} maxLength={100} /></label><label>Profession<input name="profession" defaultValue={profile.profession} maxLength={100} /></label><label>About<textarea name="about" defaultValue={profile.about} maxLength={500} /></label><label>Favourite school memory<textarea name="favouriteSchoolMemory" defaultValue={profile.favouriteSchoolMemory} maxLength={500} /></label><label>Favourite teacher or activity<input name="teacherOrActivity" defaultValue={profile.teacherOrActivity} maxLength={150} /></label><label>LinkedIn (optional)<input name="linkedin" type="url" defaultValue={profile.socialLinks?.linkedin} /></label><label>Instagram (optional)<input name="instagram" type="url" defaultValue={profile.socialLinks?.instagram} /></label><label>Website (optional)<input name="website" type="url" defaultValue={profile.socialLinks?.website} /></label><label>Avatar (optional)<input name="avatar" type="file" accept="image/jpeg,image/png,image/heic,image/webp" /></label><button type="submit">Save profile</button>{notice && <p role="status">{notice}</p>}</form><section className="panel"><h2>Your memories</h2><p className="muted">You have shared {posts} memories.</p><Link className="text-link" to="/memories">View all memories</Link></section><section className="panel form-stack"><h2>Appearance</h2><label>Theme<select value={theme} onChange={(event) => { const next = event.target.value as ThemePreference; setTheme(next); applyTheme(next) }}>{themeOptions.map((option) => <option key={option} value={option}>{option[0].toUpperCase() + option.slice(1)}</option>)}</select></label></section><section className="panel"><h2>Privacy and support</h2><p className="muted">Directory, profile, and RSVP information are private to approved batch members. You can request a correction or deletion of your profile data.</p><div className="member-actions"><button onClick={() => void requestData('correction')}>Request correction</button><button onClick={() => void requestData('deletion')}>Request deletion</button><a className="text-link" href="https://wa.me/" target="_blank" rel="noreferrer">Contact Coordinator on WhatsApp</a></div></section>{canAccessCoordinatorTools(membership?.role) && <section className="panel"><h2>Coordinator tools</h2><Link className="text-link" to="/account/coordinator">Open Coordinator tools</Link></section>}</section>
}

export function MemberProfilePage() {
  const { uid = '' } = useParams(); const { user } = useAuth(); const [profile, setProfile] = useState<MemberProfile | null>(null); const [notice, setNotice] = useState('')
  useEffect(() => { void getDoc(doc(firebaseServices().db, `batches/${PILOT_BATCH_ID}/profiles/${uid}`)).then((snapshot) => setProfile(snapshot.data() as MemberProfile ?? null)) }, [uid])
  async function report() { try { await httpsCallable(firebaseServices().functions, 'reportArchiveContent')({ batchId: PILOT_BATCH_ID, targetType: 'profile', targetId: uid, category: 'privacy', requestId: crypto.randomUUID() }); setNotice('Profile report sent to Coordinators.') } catch { setNotice('Unable to send report.') } }
  if (!profile) return <section className="empty-page"><h1>Member not found</h1></section>
  return <section className="page-stack"><Link className="text-link" to="/houses">Back to directory</Link><article className="panel"><div className="member-row"><span className="avatar">{profile.displayName.slice(0, 2).toUpperCase()}</span><span><h1>{profile.displayName}</h1><p className="muted">{profile.city}{profile.profession ? ` · ${profile.profession}` : ''}</p></span></div>{profile.about && <p>{profile.about}</p>}{profile.favouriteSchoolMemory && <p><strong>Favourite memory:</strong> {profile.favouriteSchoolMemory}</p>}{profile.teacherOrActivity && <p><strong>Teacher or activity:</strong> {profile.teacherOrActivity}</p>}<div className="member-actions">{Object.values(profile.socialLinks ?? {}).map((link) => <a key={link} className="text-link" href={link} target="_blank" rel="noreferrer">Social link</a>)}{user?.uid !== uid && <button onClick={() => void report()}>Report profile</button>}</div>{notice && <p role="status">{notice}</p>}</article></section>
}
