import { FormEvent, useEffect, useState } from 'react'
import { collection, doc, getDoc, getDocs } from 'firebase/firestore/lite'
import { httpsCallable } from 'firebase/functions'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { formatIndianDate } from '../lib/dateFormat'
import { firebaseServices } from '../lib/firebase'
import { PILOT_BATCH_ID } from '../lib/membership'
type Reunion = { title?: string; venue?: string; instructions?: string; rsvpCutoffAt?: { toDate: () => Date } }
type Rsvp = { attendance?: string; accompanyingAdults?: number; accompanyingChildren?: number; foodPreference?: string; hotelRequired?: boolean; miscellaneousDetails?: string }
export function ReunionPage() {
  const { user } = useAuth(); const [config, setConfig] = useState<Reunion>({}); const [rsvp, setRsvp] = useState<Rsvp>({ attendance: 'maybe', accompanyingAdults: 0, accompanyingChildren: 0, foodPreference: 'notSpecified', hotelRequired: false }); const [attendance, setAttendance] = useState({ yes: 0, maybe: 0 }); const [notice, setNotice] = useState('')
  useEffect(() => { const db = firebaseServices().db; void Promise.all([getDoc(doc(db, `batches/${PILOT_BATCH_ID}/reunion/config`)), user && getDoc(doc(db, `batches/${PILOT_BATCH_ID}/rsvps/${user.uid}`)), getDocs(collection(db, `batches/${PILOT_BATCH_ID}/rsvps`))]).then(([reunion, ownRsvp, responses]) => { setConfig(reunion.data() ?? {}); if (ownRsvp?.exists()) setRsvp(ownRsvp.data()); setAttendance(responses.docs.reduce((total, item) => { const value: unknown = item.data().attendance; if (value === 'yes') return { yes: total.yes + 1, maybe: total.maybe }; if (value === 'maybe') return { yes: total.yes, maybe: total.maybe + 1 }; return total }, { yes: 0, maybe: 0 })) }) }, [user])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); try { await httpsCallable(firebaseServices().functions, 'submitRsvp')({ batchId: PILOT_BATCH_ID, attendance: values.get('attendance'), accompanyingAdults: Number(values.get('adults')), accompanyingChildren: Number(values.get('children')), foodPreference: values.get('food'), hotelRequired: values.get('hotel') === 'on', miscellaneousDetails: values.get('details') }); setNotice('RSVP saved.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to save RSVP.') } }
  const cutoff = config.rsvpCutoffAt?.toDate()
  return <section className="page-stack"><div className="hero-card"><div className="hero-content"><p className="eyebrow">January 2027</p><h1>{config.title ?? 'Silver Jubilee Reunion'}</h1><p className="hero-caption">{config.venue ?? 'Venue details will be announced shortly.'}</p></div></div><section className="panel"><h2>Reunion fund</h2><p className="muted">Contributions and transparent approved-expense reporting live inside the reunion hub.</p><Link className="text-link" to="/reunion/fund">View reunion fund</Link></section><section className="panel"><h2>Who’s coming</h2><p className="muted">{attendance.yes} confirmed · {attendance.maybe} maybe</p></section><div className="panel"><h2>RSVP</h2><p className="muted">{cutoff ? `Please respond by ${formatIndianDate(cutoff)}.` : 'Please let the Coordinators know your plans.'}</p><form className="form-stack" key={JSON.stringify(rsvp)} onSubmit={submit}><label>Will you attend?<select name="attendance" defaultValue={rsvp.attendance}><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">No</option></select></label><div className="field-row"><label>Accompanying adults<input name="adults" type="number" min="0" defaultValue={rsvp.accompanyingAdults} /></label><label>Children<input name="children" type="number" min="0" defaultValue={rsvp.accompanyingChildren} /></label></div><label>Food preference<select name="food" defaultValue={rsvp.foodPreference}><option value="notSpecified">Not specified</option><option value="vegetarian">Vegetarian</option><option value="nonVegetarian">Non-vegetarian</option></select></label><label className="check-label"><input name="hotel" type="checkbox" defaultChecked={rsvp.hotelRequired} /> I need accommodation</label><label>Anything else?<textarea name="details" maxLength={1000} defaultValue={rsvp.miscellaneousDetails} /></label><button type="submit">Save RSVP</button>{notice && <p role="status">{notice}</p>}</form></div>{config.instructions && <article className="panel"><h2>Instructions</h2><p className="muted">{config.instructions}</p></article>}</section>
}
