import { assertFails, assertSucceeds, initializeTestEnvironment, RulesTestEnvironment } from '@firebase/rules-unit-testing'
import { readFileSync } from 'node:fs'
import { afterAll, beforeAll, beforeEach, describe, it } from 'vitest'

const projectId = 'demo-no-project'
let environment: RulesTestEnvironment
const db = (uid?: string) => uid ? environment.authenticatedContext(uid).firestore() : environment.unauthenticatedContext().firestore()
beforeAll(async () => { environment = await initializeTestEnvironment({ projectId, firestore: { rules: readFileSync('firestore.rules', 'utf8') }, storage: { rules: readFileSync('storage.rules', 'utf8') } }) })
beforeEach(async () => { await environment.clearFirestore(); await environment.clearStorage(); await environment.withSecurityRulesDisabled(async (context) => {
  const admin = context.firestore()
  await admin.doc('batches/batch-a').set({ name: 'A' }); await admin.doc('batches/batch-b').set({ name: 'B' })
  await admin.doc('batches/batch-a/memberships/member').set({ status: 'active', role: 'batchmate' })
  await admin.doc('batches/batch-a/memberships/coordinator').set({ status: 'active', role: 'coordinator' })
  await admin.doc('batches/batch-a/memberships/pending').set({ status: 'pending', role: 'batchmate' })
  await admin.doc('batches/batch-a/memberships/suspended').set({ status: 'suspended', role: 'batchmate' })
  await admin.doc('batches/batch-b/memberships/other-batch').set({ status: 'active', role: 'batchmate' })
  await admin.doc('batches/batch-a/profiles/member').set({ uid: 'member', displayName: 'Member' })
  await admin.doc('batches/batch-a/profiles/coordinator').set({ uid: 'coordinator', displayName: 'Coordinator' })
  await admin.doc('batches/batch-a/reunion/config').set({ rsvpCutoffAt: new Date('2027-01-01') })
  await admin.doc('batches/batch-a/paymentClaims/claim').set({ memberUid: 'member', utr: 'UTR' })
  await admin.doc('batches/batch-a/fundSummary/public').set({ collectedPaise: 10000, balancePaise: 10000 })
  await admin.doc('batches/batch-a/expenses/approved').set({ status: 'approved', category: 'Venue', amountPaise: 5000 })
  await admin.doc('batches/batch-a/expenses/draft').set({ status: 'draft', category: 'Venue', amountPaise: 5000 })
  await admin.doc('batches/batch-a/posts/visible').set({ authorUid: 'member', status: 'visible', caption: 'A memory' })
  await admin.doc('batches/batch-a/posts/hidden').set({ authorUid: 'member', status: 'hidden', caption: 'Hidden memory' })
  await admin.doc('batches/batch-a/posts/visible/comments/comment').set({ authorUid: 'member', body: 'Nice', status: 'visible' })
  await admin.doc('batches/batch-a/albums/visible').set({ authorUid: 'member', status: 'visible', title: 'Archive' })
  await admin.doc('batches/batch-a/notifications/member/items/payment').set({ title: 'Payment verified', body: 'Done', kind: 'payment' })
}) })
afterAll(async () => { if (environment) await environment.cleanup() })
describe('private batch boundaries', () => {
  it('denies unauthenticated and pending reads', async () => { const anonymous = db(); const pending = db('pending'); await assertFails(anonymous.doc('batches/batch-a/profiles/member').get()); await assertFails(pending.doc('batches/batch-a/profiles/member').get()) })
  it('revokes private access immediately for suspended members', async () => { await assertFails(db('suspended').doc('batches/batch-a/profiles/member').get()) })
  it('allows active members only within their batch', async () => { const member = db('member'); const otherBatch = db('other-batch'); await assertSucceeds(member.doc('batches/batch-a/profiles/member').get()); await assertFails(otherBatch.doc('batches/batch-a/profiles/member').get()) })
  it('keeps payment claims Coordinator-only', async () => { const member = db('member'); const coordinator = db('coordinator'); await assertFails(member.doc('batches/batch-a/paymentClaims/claim').get()); await assertSucceeds(coordinator.doc('batches/batch-a/paymentClaims/claim').get()) })
  it('exposes only aggregate finances and approved expenses to batchmates', async () => {
    const member = db('member')
    await assertSucceeds(member.doc('batches/batch-a/fundSummary/public').get())
    await assertSucceeds(member.doc('batches/batch-a/expenses/approved').get())
    await assertFails(member.doc('batches/batch-a/expenses/draft').get())
  })
  it('denies client writes to finance state and audit records', async () => {
    const member = db('member'); const coordinator = db('coordinator')
    await assertFails(member.doc('batches/batch-a/fundSummary/public').set({ collectedPaise: 999999 }))
    await assertFails(member.doc('batches/batch-a/paymentClaims/new').set({ status: 'verified' }))
    await assertFails(coordinator.doc('batches/batch-a/auditEvents/new').set({ action: 'finance.verified' }))
  })
  it('keeps audit events unreadable to every browser client, including Coordinators', async () => {
    await environment.withSecurityRulesDisabled(async (context) => context.firestore().doc('batches/batch-a/auditEvents/event').set({ action: 'coordinator.assigned' }))
    await assertFails(db('member').doc('batches/batch-a/auditEvents/event').get())
    await assertFails(db('coordinator').doc('batches/batch-a/auditEvents/event').get())
  })
  it('does not permit a client to grant a Coordinator role', async () => { const member = db('member'); await assertFails(member.doc('batches/batch-a/memberships/member').set({ status: 'active', role: 'coordinator' })) })
  it('does not give a Super Admin claim direct batch access or role-write access', async () => {
    const superAdmin = environment.authenticatedContext('super-admin', { superAdmin: true }).firestore()
    await assertFails(superAdmin.doc('batches/batch-a/profiles/member').get())
    await assertFails(superAdmin.doc('batches/batch-a/memberships/member').update({ role: 'coordinator' }))
  })
  it('allows only the requester to create a constrained access request', async () => {
    const requester = db('requester')
    const request = { uid: 'requester', batchId: 'batch-a', displayName: 'Requesting Member', houseId: 'tilak', rollNumber: '3711', passingYear: 2002, status: 'pending', createdAt: new Date(), updatedAt: new Date() }
    await assertSucceeds(requester.doc('batches/batch-a/accessRequests/requester').set(request))
    await assertFails(requester.doc('batches/batch-a/accessRequests/forged').set({ ...request, uid: 'member' }))
    await assertFails(requester.doc('batches/batch-a/accessRequests/invalid').set({ ...request, houseId: 'unknown' }))
  })
  it('allows rejected requests to be corrected and resubmitted without changing protected review fields', async () => {
    await environment.withSecurityRulesDisabled(async (context) => context.firestore().doc('batches/batch-a/accessRequests/requester').set({ uid: 'requester', batchId: 'batch-a', displayName: 'Wrong Name', houseId: 'tilak', rollNumber: '3711', passingYear: 2002, status: 'rejected', rejectionReason: 'Please use your full name.', rejectedBy: 'coordinator', rejectedAt: new Date(), createdAt: new Date(), updatedAt: new Date() }))
    const requester = db('requester')
    await assertSucceeds(requester.doc('batches/batch-a/accessRequests/requester').update({ displayName: 'Correct Name', rollNumber: '3712', status: 'pending', resubmittedAt: new Date(), updatedAt: new Date() }))
    await assertFails(requester.doc('batches/batch-a/accessRequests/requester').update({ rejectionReason: 'forged' }))
  })
  it('lets a member edit only their own profile without changing their house', async () => {
    const member = db('member')
    await assertSucceeds(member.doc('batches/batch-a/profiles/member').update({ city: 'Pune' }))
    await assertFails(member.doc('batches/batch-a/profiles/member').update({ houseId: 'tilak' }))
    await assertFails(member.doc('batches/batch-a/profiles/coordinator').update({ city: 'Pune' }))
    await assertFails(member.doc('batches/batch-a/profiles/member').update({ socialLinks: { website: 'javascript:alert(1)' } }))
  })
  it('keeps RSVP attendance summaries batch-private', async () => {
    await environment.withSecurityRulesDisabled(async (context) => context.firestore().doc('batches/batch-a/rsvps/member').set({ uid: 'member', attendance: 'yes' }))
    await assertSucceeds(db('member').doc('batches/batch-a/rsvps/member').get())
    await assertFails(db('pending').doc('batches/batch-a/rsvps/member').get())
  })
  it('limits reunion configuration to Coordinators and RSVP writes to trusted functions', async () => {
    await assertFails(db('member').doc('batches/batch-a/reunion/config').update({ title: 'Changed' }))
    await assertSucceeds(db('coordinator').doc('batches/batch-a/reunion/config').update({ title: 'Silver Jubilee' }))
    await assertFails(db('member').doc('batches/batch-a/rsvps/member').set({ attendance: 'yes' }))
  })
  it('keeps schedule and operational contacts batch-private while allowing Coordinator configuration', async () => {
    const member = db('member'); const coordinator = db('coordinator'); const pending = db('pending')
    await assertSucceeds(coordinator.doc('batches/batch-a/reunionSchedule/welcome').set({ title: 'Welcome', startsAt: new Date() }))
    await assertSucceeds(coordinator.doc('batches/batch-a/reunionContacts/help').set({ name: 'Help desk', phone: '123' }))
    await assertSucceeds(member.doc('batches/batch-a/reunionSchedule/welcome').get())
    await assertSucceeds(member.doc('batches/batch-a/reunionContacts/help').get())
    await assertFails(member.doc('batches/batch-a/reunionSchedule/forged').set({ title: 'Forged' }))
    await assertFails(pending.doc('batches/batch-a/reunionContacts/help').get())
  })
  it('requires configured contribution heads when a Coordinator saves payment instructions', async () => {
    const coordinator = db('coordinator')
    const base = { defaultFamilyAmountPaise: 10000, targetPaise: 50000, currency: 'INR', upiId: 'collection@upi', qrStoragePath: 'batches/batch-a/reunion/qr/code.png', updatedBy: 'coordinator', updatedAt: new Date() }
    await assertFails(coordinator.doc('batches/batch-a/paymentConfig/current').set(base))
    await assertSucceeds(coordinator.doc('batches/batch-a/paymentConfig/current').set({ ...base, contributionHeads: ['Reunion contribution'] }))
  })
  it('shows only visible archive content to active batch members', async () => {
    const member = db('member')
    await assertSucceeds(member.doc('batches/batch-a/posts/visible').get())
    await assertFails(member.doc('batches/batch-a/posts/hidden').get())
    await assertSucceeds(member.doc('batches/batch-a/posts/visible/comments/comment').get())
    await assertSucceeds(member.doc('batches/batch-a/albums/visible').get())
  })
  it('keeps reports and archive mutations behind trusted moderation operations', async () => {
    const member = db('member'); const coordinator = db('coordinator')
    await assertFails(member.doc('batches/batch-a/posts/new').set({ authorUid: 'member', status: 'visible' }))
    await assertFails(member.doc('batches/batch-a/reports/new').set({ targetType: 'post' }))
    await assertFails(member.doc('batches/batch-a/reports/new').get())
    await assertSucceeds(coordinator.doc('batches/batch-a/reports/new').get())
  })
  it('keeps each notification centre private and server-written', async () => {
    await assertSucceeds(db('member').doc('batches/batch-a/notifications/member/items/payment').get())
    await assertFails(db('coordinator').doc('batches/batch-a/notifications/member/items/payment').get())
    await assertFails(db('member').doc('batches/batch-a/notifications/member/items/forged').set({ title: 'Forged' }))
  })
  it('allows only an active post author to upload permitted archive media', async () => {
    const memberStorage = environment.authenticatedContext('member').storage()
    const otherStorage = environment.authenticatedContext('other-batch').storage()
    await assertSucceeds(memberStorage.ref('batches/batch-a/posts/visible/media/photo.jpg').putString('photo', 'raw', { contentType: 'image/jpeg' }))
    await assertFails(otherStorage.ref('batches/batch-a/posts/visible/media/photo.jpg').putString('photo', 'raw', { contentType: 'image/jpeg' }))
    await assertFails(memberStorage.ref('batches/batch-a/posts/visible/media/file.pdf').putString('pdf', 'raw', { contentType: 'application/pdf' }))
  })
  it('allows only the profile owner to upload an avatar', async () => {
    const memberStorage = environment.authenticatedContext('member').storage()
    const coordinatorStorage = environment.authenticatedContext('coordinator').storage()
    await assertSucceeds(memberStorage.ref('batches/batch-a/profiles/member/avatar/photo.jpg').putString('photo', 'raw', { contentType: 'image/jpeg' }))
    await assertFails(coordinatorStorage.ref('batches/batch-a/profiles/member/avatar/photo.jpg').putString('photo', 'raw', { contentType: 'image/jpeg' }))
  })
})
