import { lazy, Suspense } from 'react'
import { Navigate, Route, Routes } from 'react-router-dom'
import { AccessRequest } from './auth/AccessRequest'
import { useAuth } from './auth/AuthProvider'
import { BatchShell } from './batch/BatchShell'
import { destinationForSession, canAccessMemberFlow, canAccessSuperAdminRoute } from './lib/authorization'
import { COPY } from './lib/copy'
import { HomePage } from './batch/HomePage'
import { SuperAdminConsole } from './superAdmin/SuperAdminConsole'
const CoordinatorPage = lazy(async () => ({ default: (await import('./batch/CoordinatorPage')).CoordinatorPage }))
const HousesPage = lazy(async () => ({ default: (await import('./batch/HousesPage')).HousesPage }))
const ProfilePage = lazy(async () => ({ default: (await import('./batch/ProfilePage')).ProfilePage }))
const MemberProfilePage = lazy(async () => ({ default: (await import('./batch/ProfilePage')).MemberProfilePage }))
const ReunionPage = lazy(async () => ({ default: (await import('./batch/ReunionPage')).ReunionPage }))
const FinancePage = lazy(async () => ({ default: (await import('./batch/FinancePage')).FinancePage }))
const MemoriesPage = lazy(async () => ({ default: (await import('./batch/MemoriesPage')).MemoriesPage }))
function Landing() { const { user, membership, isSuperAdmin, signIn, signInForE2E } = useAuth(); if (user && isSuperAdmin) return <Navigate to="/super-admin" replace />; if (user && membership) return <Navigate to={destinationForSession(false, membership)} replace />; return <main className="auth-card"><p className="eyebrow">{COPY.batchName}</p><h1>25 years. One brotherhood.</h1><p>{COPY.privateAccess}</p><button onClick={() => void signIn()}>{COPY.signIn}</button>{import.meta.env.VITE_E2E_AUTH === 'true' && <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void signInForE2E(String(form.get('email')), String(form.get('password'))) }}><label>Test email<input name="email" type="email" /></label><label>Test password<input name="password" type="password" /></label><button type="submit">Test sign in</button></form>}</main> }
function Pending() { return <main className="auth-card"><h1>Approval pending</h1><p>A Coordinator will review your request. Private batch data remains unavailable until approval.</p></main> }
function Denied() { return <main className="auth-card"><h1>Access unavailable</h1><p>Your batch access is not active. Please contact a Coordinator on WhatsApp.</p></main> }
function Protected() { const { user, membership, isSuperAdmin, loading } = useAuth(); if (loading) return <main className="auth-card">Loading secure session…</main>; if (!user || !membership) return <Navigate to="/" replace />; if (!canAccessMemberFlow(isSuperAdmin)) return <Navigate to="/super-admin" replace />; const destination = destinationForSession(false, membership); return destination === '/home' ? <BatchShell /> : <Navigate to={destination} replace /> }
function CoordinatorOnly() { return <CoordinatorPage /> }
function SignedInMemberOnly({ children }: { children: React.ReactNode }) { const { user, isSuperAdmin, loading } = useAuth(); if (loading) return <main className="auth-card">Loading secure session…</main>; if (!user) return <Navigate to="/" replace />; return canAccessMemberFlow(isSuperAdmin) ? children : <Navigate to="/super-admin" replace /> }
function SuperAdminOnly() { const { user, isSuperAdmin, loading } = useAuth(); if (loading) return <main className="auth-card">Loading secure session…</main>; return canAccessSuperAdminRoute(Boolean(user), isSuperAdmin) ? <SuperAdminConsole /> : <Navigate to="/" replace /> }
export default function App() { return <Suspense fallback={<main className="auth-card" role="status">Loading secure screen…</main>}><Routes><Route path="/" element={<Landing />} /><Route path="/super-admin" element={<SuperAdminOnly />} /><Route path="/admin" element={<Navigate to="/super-admin" replace />} /><Route path="/request-access" element={<SignedInMemberOnly><AccessRequest /></SignedInMemberOnly>} /><Route path="/pending" element={<SignedInMemberOnly><Pending /></SignedInMemberOnly>} /><Route path="/access-denied" element={<SignedInMemberOnly><Denied /></SignedInMemberOnly>} /><Route element={<Protected />}><Route path="/home" element={<HomePage />} /><Route path="/houses" element={<HousesPage />} /><Route path="/members/:uid" element={<MemberProfilePage />} /><Route path="/reunion" element={<ReunionPage />} /><Route path="/reunion/fund" element={<FinancePage />} /><Route path="/memories" element={<MemoriesPage />} /><Route path="/account" element={<ProfilePage />} /><Route path="/account/coordinator" element={<CoordinatorOnly />} /><Route path="/fund" element={<Navigate to="/reunion/fund" replace />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></Suspense> }
